import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { resolve, relative } from 'node:path';
const root=fileURLToPath(new URL('../',import.meta.url)),dist=resolve(root,'dist'),out=resolve(root,'render-host');
const assets={};
function collect(dir){for(const entry of readdirSync(dir,{withFileTypes:true})){const path=resolve(dir,entry.name);if(entry.isDirectory())collect(path);else assets[relative(dist,path).replaceAll('\\','/')]=readFileSync(path).toString('base64');}}
collect(dist);mkdirSync(out,{recursive:true});
function source(file){return readFileSync(resolve(root,file),'utf8').replace(/^import .* from ['"]\.\.?\/.*['"];\n/gm,'').replace(/^export (?=(?:function|const|class|async function)\b)/gm,'');}
const code='// Cá Ngựa Club 2.1 — standalone Render host. Generated by scripts/build-host.mjs.\n// Includes the complete PWA and offline 3D assets. Node.js 22+.\n'
  +'/*\n'+readFileSync(resolve(root,'THIRD-PARTY-NOTICES.txt'),'utf8').replaceAll('*/','* /')+'\n*/\n'
  +source('dist/engine.mjs')+'\n'+source('dist/network.mjs')+'\n'+source('room-store.mjs')+'\n'+source('host-core.mjs')+'\n'
  +'startHost({assets:'+JSON.stringify(assets)+'});\n';
writeFileSync(resolve(out,'host.mjs'),code);
writeFileSync(resolve(out,'package.json'),JSON.stringify({name:'ca-ngua-pwa-host',version:'2.1.1',private:true,type:'module',engines:{node:'>=22'},scripts:{start:'node host.mjs'}},null,2)+'\n');
console.log(`Built render-host/host.mjs: ${Object.keys(assets).length} embedded assets, ${Buffer.byteLength(code)} bytes.`);
